### ISSUE TITLE
No way to properly shutdown/kill gdcrm

### ISSUE THREAD

**Issue by Iruwen** [fsn-dev/dcrm-walletService#2]
None of the kill signals normally used to trigger a clean shutdown (e.g. SIGHUP, SIGINT, SIGTERM) causes gdcrm to end with exit code 0. That causes all kinds of issues with scripting and restart policies, for example with systemd or Docker.
To be in line with Linux/POSIX standards and to avoid workarounds, and to guarantee the integrity of the database because otherwise a hard kill will be enforced after the given timeout, the service should initiate a clean exit with code 0 as it receives SIGTERM (signal 15), unless an actual error occurs.

**Comment by haijuncai** [comment]
fixed,   commit id: 48775c3f36a9936e7cd6f6aaf8c7e6607b1071b0  on  branch dev

**Comment by Iruwen** [comment]
![image](https://user-images.githubusercontent.com/11341130/88518215-631a7380-cff0-11ea-8e2b-6a9027f74f0e.png)

Flawless, thank you.
